baseURL = "https://hpblogging.netlify.app/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "HP Blogging"
theme = "anatole"
summarylength = 25
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Hansel Palencia"
#author = "HPBlogging"
description = "Happy Husband, Future Father, and Data Scientist"
profilePicture = "images/mypiccrop.jpg"
keywords = ""
favicon = "images/mypiccrop.png"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/mypiccrop.png"]
# Google Site Verification
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/hanselpalencia/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://https://github.com/HanselPalencia"

#[[params.socialIcons]]
#icon = "fa-instagram"
#title = "instagram"
#url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:hanselpalencia@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
